tokens:
  access-token-uri: https://token.services.auth.zalando.com/oauth2/access_token?realm=/services
  token-info-uri: https://info.services.auth.zalando.com/oauth2/tokeninfo
  credentials-directory: ${user.dir}/credentials
  token-configuration-list:
   - token-id: kio
     scopes:
      - uid
