tokens:
  autoStartup: false
  access-token-uri: https://token.services.auth.zalando.com/oauth2/access_token?realm=/services
  credentials-directory: ${user.home}/.berry/pazuzu-registry
  token-info-uri: https://info.services.auth.zalando.com/oauth2/tokeninfo
  token-configuration-list:
   - token-id: kio
     scopes:
      - uid
security:
  basic:
    enabled: false
